# Example of a scheduled job that commits new data file

name: append every three mins

# Schedule a job
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/3 * * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo I am running now

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create data and append
        run: |
          python do.py

      - name: Commit data files  
        run: |
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git add timestamp.py
          git commit -m "new data from scheduled job"

      - name: Push changes  #
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

